kind: pipeline
type: docker
name: API_Fantom_Games_Connection


trigger:
  event:
    - push


steps:
  # building server
  - name: build
    image: node:14
    commands:
      - cd Source/server
      - npm install -f
      - npm build

  # testing server
  - name: server-test
    image: node:14
    commands :
      - cd Source/server
      - npm install; npm start &
      - sleep 5
      - if [ -z "$(curl -s http://localhost:3000 | grep '<pre>Cannot GET /</pre>')" ];then exit 1;fi

    depends_on: [ build ]