kind: pipeline
type: docker
name: API_Fantom_Games_Connection


trigger:
  event:
    - push


steps:
  # building server
  - name: build
    image: node:14
    commands:
      - cd Source/server
      - npm install -f
      - npm build

  # testing server
  - name: server-test
    image: node:14
    commands :
      - cd Source/server
      - npm install
      - npm start &
      - sleep 5
      - curl -I localhost:3000
    depends_on: [ build ]

  # docker image build
  - name: set_server
    image: plugins/docker
    settings:
      dockerfile: ./Source/Dockerfile
      context: ./Source
      registry: hub.codefirst.iut.uca.fr
      repo: hub.codefirst.iut.uca.fr/dorian.hodin/socketioservergames
      username:
        from_secret: SECRET_USERNAME
      password:
        from_secret: SECRET_PASSWD
    depends_on: [ server-test ]


  # container deployment
  - name: deploy_api
    image: hub.codefirst.iut.uca.fr/thomas.bellembois/codefirst-dockerproxy-clientdrone:latest
    environment:
      IMAGENAME: hub.codefirst.iut.uca.fr/dorian.hodin/socketioservergames:latest
      CONTAINERNAME: deploy_server
      COMMAND: create
      OVERWRITE: true
      ADMINS: dorianhodin,corentinrichard,jeremybesson,joanpierron,baptistemarcel
    depends_on: [ set_server ]
